# Generated by Django 5.1.3 on 2024-11-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('red_beans', models.FloatField()),
                ('maize', models.FloatField()),
                ('peas', models.FloatField()),
                ('coffee', models.FloatField()),
                ('milk', models.FloatField()),
                ('avocados', models.FloatField()),
                ('cassava', models.FloatField()),
                ('sweet_potatoes', models.FloatField()),
                ('irish_potatoes', models.FloatField()),
                ('pumpkins', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agriculture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
