# Generated by Django 5.1.3 on 2024-12-06 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_agriculturedata_bananas_agriculturedata_oranges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturedata',
            name='is_avocados_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_bananas_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_cassava_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_coffee_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_irish_potatoes_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_maize_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_milk_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_oranges_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_peas_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_plantains_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_pumpkins_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_red_beans_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_rice_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='is_sweet_potatoes_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agriculturedata',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0)),
        ),
    ]
