# Generated by Django 5.1.3 on 2024-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('from_account', models.CharField(max_length=255)),
                ('to_account', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('fee', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
