# Generated by Django 5.1.3 on 2024-12-10 06:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('weight_type', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], max_length=2)),
                ('waist', models.FloatField()),
                ('waist_choices', models.CharField(choices=[('cm', 'cm'), ('in', 'in')], max_length=2)),
                ('smoking_status', models.BooleanField(default=False)),
                ('vaping_status', models.BooleanField(default=False)),
                ('blood_pressure', models.FloatField()),
                ('a1c_level', models.FloatField()),
                ('blood_sugar_level', models.FloatField()),
                ('pregnant', models.BooleanField(default=False)),
                ('malaria', models.BooleanField(default=False)),
                ('covid', models.BooleanField(default=False)),
                ('is_height_selling', models.BooleanField(default=False)),
                ('is_weight_selling', models.BooleanField(default=False)),
                ('is_waist_selling', models.BooleanField(default=False)),
                ('is_smoking_status_selling', models.BooleanField(default=False)),
                ('is_vaping_status_selling', models.BooleanField(default=False)),
                ('is_blood_pressure_selling', models.BooleanField(default=False)),
                ('is_a1c_level_selling', models.BooleanField(default=False)),
                ('is_blood_sugar_level_selling', models.BooleanField(default=False)),
                ('is_pregnant_selling', models.BooleanField(default=False)),
                ('is_malaria_selling', models.BooleanField(default=False)),
                ('is_covid_selling', models.BooleanField(default=False)),
                ('last_updated_time', models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0))),
                ('fhir_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
