# Generated by Django 5.1.3 on 2024-12-13 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthprofile',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0)),
        ),
    ]
