# Generated by Django 5.1.3 on 2024-12-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
