# Generated by Django 5.1.3 on 2024-12-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_contractrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthprofile',
            name='blood_pressure',
            field=models.CharField(default='129/80', max_length=7),
        ),
    ]
