# Generated by Django 5.1.3 on 2024-12-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_userhealthprofile_blood_pressure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='owner',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='contractrecipient',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_secret',
        ),
        migrations.AddField(
            model_name='contractrecipient',
            name='contract_secret',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractrecipient',
            name='data_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
