# Generated by Django 5.1.3 on 2024-12-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_rename_owner_contract_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
        migrations.AddField(
            model_name='contractrecipient',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
