# Generated by Django 5.1.3 on 2024-12-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_remove_contract_price_contractrecipient_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrecipient',
            name='contract_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
