# Generated by Django 5.1.3 on 2024-12-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_alter_contractrecipient_contract_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrecipient',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
