# Generated by Django 5.1.4 on 2025-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_contractrecipient_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrecipient',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='media/health/'),
        ),
    ]
