# Generated by Django 5.1.4 on 2025-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_contractrecipient_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrecipient',
            name='data_file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
