# Generated by Django 5.1.4 on 2025-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_alter_contractrecipient_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrecipient',
            name='data_file',
        ),
        migrations.AddField(
            model_name='contract',
            name='data_file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
