# Generated by Django 5.1.4 on 2025-01-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_userhealthprofile_bmi_percentile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_bmi_percentile_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_body_temperature_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_heart_rate_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_pulse_oximetry_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_respiratory_rate_selling',
            field=models.BooleanField(default=False),
        ),
    ]
