# Generated by Django 5.1.4 on 2025-01-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_userhealthprofile_is_bmi_percentile_selling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthprofile',
            name='bmi_percentile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='heart_rate',
            field=models.IntegerField(blank=True, default=75, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='pulse_oximetry',
            field=models.IntegerField(blank=True, default=98, null=True),
        ),
    ]
