# Generated by Django 5.1.3 on 2024-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
