# Generated by Django 5.1.4 on 2025-01-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('organization_name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('organization_type', models.CharField(max_length=128)),
                ('stripe_subscription_id', models.CharField(max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
