# Generated by Django 5.1.3 on 2024-12-27 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculture', '0004_alter_agriculturedata_modified_contract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('is_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_buyer', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('contract', 'contract')], max_length=10, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_notification', to='agriculture.contract')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('notification_recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notification.notification')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_5fc2a8_idx'), models.Index(fields=['notification', 'recipient'], name='notificatio_notific_e8a391_idx')],
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
