# Generated by Django 5.1.3 on 2024-12-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('data_points', models.TextField(blank=True, null=True)),
                ('to_buyer', models.BooleanField(default=False)),
                ('is_all', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_id', models.CharField(blank=True, max_length=64, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
