# Generated by Django 5.1.3 on 2024-12-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_contract'),
        ('notification', '0002_rename_title_notification_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='data_points',
        ),
        migrations.AddField(
            model_name='notification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_notification', to='health.contract'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('contract', 'contract')], max_length=10, null=True),
        ),
    ]
