# Generated by Django 5.1.3 on 2024-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_all',
            field=models.BooleanField(default=False),
        ),
    ]
