# Generated by Django 5.1.2 on 2024-10-25 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('weight_type', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], max_length=2)),
                ('waist', models.FloatField()),
                ('waist_choices', models.CharField(choices=[('cm', 'cm'), ('in', 'in')], max_length=2)),
                ('smoking_status', models.BooleanField(default=False)),
                ('vaping_status', models.BooleanField(default=False)),
                ('blood_pressure', models.FloatField()),
                ('a1c_level', models.FloatField()),
                ('blood_sugar_level', models.FloatField()),
                ('pregnant', models.BooleanField(default=False)),
                ('malaria', models.BooleanField(default=False)),
                ('covid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
