# Generated by Django 5.1.3 on 2024-12-06 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_a1c_level_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_blood_pressure_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_blood_sugar_level_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_covid_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_height_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_malaria_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_pregnant_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_smoking_status_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_vaping_status_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_waist_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_weight_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='last_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0)),
        ),
    ]
