# Generated by Django 5.1.3 on 2024-12-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userhealthprofile_is_a1c_level_selling_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHealthProfile',
        ),
    ]
