# Generated by Django 5.1.4 on 2024-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userprofile_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
