from django.urls import path,re_path,include
from rest_framework.routers import SimpleRouter
from user.views import (
    UserRegistrationView,
    UserRegistrationMobileView,
    EmailVerificationView,
    UserLoginView,
    TOTPCreateView,
    TOTPVerifyView,
    ResendEmailVerificationView,
    UserLogoutView,
    EmailObtainView,
    UserTokenRefreshView,
    UserNameObtainView,
    ProfileView,
    TOTPRecoveryView,
    PolicyView,
    UserWalletViewSet,
    ForgotPasswordView,
    PasswordResetView,
    MobileObtainView,
    MobileVerificationView,
    ResendMobileVerificationView,
    UserLoginMobileView,
    ForgotPasswordMobileView,
    UserModeView,
    ChangeUserModeView,
    BuyerSpentView,
    SellerRevenueView,
    BuyerContractView
)
# router = SimpleRouter(trailing_slash=False)

urlpatterns = [
    path('register', UserRegistrationView.as_view(), name='register_user'),
    path('register_mobile', UserRegistrationMobileView.as_view(), name='register_user_mobile'),
    path("activate", EmailVerificationView.as_view(), name="activate_user"),
    path("activate_mobile", MobileVerificationView.as_view(), name="activate_user_mobile"),
    path('login', UserLoginView.as_view(), name='login'),
    path('login_mobile', UserLoginMobileView.as_view(), name='login_mobile'),
    path('totp/create', TOTPCreateView.as_view(), name='totp_create'),
    path('totp/login', TOTPVerifyView.as_view(), name='totp_login'),
    # re_path(r'^totp/create/(?P<auth_token>[\w\-_=]+)/$', TOTPCreateView.as_view(), name='totp_create'),
    # re_path(r'^totp/login/(?P<auth_token>[\w\-_=]+)/$', TOTPVerifyView.as_view(), name='totp_login'),
    path('resend_email', ResendEmailVerificationView.as_view(), name='resend_verification'),
    path('resend_sms', ResendMobileVerificationView.as_view(), name='resend_sms_verification'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('check_email',EmailObtainView.as_view(),name='check_email'),
    path('check_mobile',MobileObtainView.as_view(),name='check_mobile'),
    path('refresh_token',UserTokenRefreshView.as_view(),name='refresh_token'),
    path('check_user',UserNameObtainView.as_view(),name='check_user'),
    path('profile',ProfileView.as_view(),name='profile_create_update_get'),
    path('totp/recovery', TOTPRecoveryView.as_view(), name='totp_recovery'),
    path('policy', PolicyView.as_view(), name='policy'),
    path('wallet', UserWalletViewSet.as_view(), name='wallet'  ),
    path('forgot_password', ForgotPasswordView.as_view(), name='forgot_password'),
    path('forgot_password_mobile', ForgotPasswordMobileView.as_view(), name='forgot_password_mobile'),
    path("reset_verify", PasswordResetView.as_view(), name="reset_verify"),
    path('get_user_mode',UserModeView.as_view(),name="get_user_mode"),
    path('change_user_mode',ChangeUserModeView.as_view(),name="change_user_mode"),
    path('buyer_spent',BuyerSpentView.as_view(),name="buyer_spent"),
    path('seller_revenue',SellerRevenueView.as_view(),name="seller_revenue"),
    path('buyer_contracts',BuyerContractView.as_view(),name="buyer_contracts"),
]